language: node_js
node_js:
  - "node"

cache: npm

script: npm run build
after_script:
  - cd ./dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

deploy:
provider: pages
skip_cleanup: true
github_token: $GH_TOKEN
#local_dir: dist
target_branch: gh-pages
on:
  branch: master