language: node_js
node_js:
  - "node"

cache: npm

script: npm run build
after_script:
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f git@github.com:fyiloutingfengyu/f-vue-typescript.git master:gh-pages

deploy:
provider: pages
skip_cleanup: true
github_token: $GH_TOKEN
#local_dir: dist
target_branch: gh-pages
on:
  branch: master